import type { Metadata, Viewport } from "next";
import { Funnel_Display, Funnel_Sans, Instrument_Serif } from "next/font/google";
import { Analytics } from "@vercel/analytics/next";
import { SpeedInsights } from "@vercel/speed-insights/next";

import { Motion } from "@/components/motion/Motion";
import { QrDefs } from "@/components/QrCode";
import { OrganizationSchema, WebSiteSchema } from "@/components/seo/JsonLd";
import { isProductionSite, site, verification } from "@/lib/site";
import "./globals.css";

/**
 * Fonts are self-hosted by next/font at build time (the CSP blocks font CDNs),
 * with `display: swap` and generated fallback metrics so the swap doesn't
 * shift layout. All three render above the fold, so all three are preloaded.
 *
 * - Funnel Display: headings only, and only at 800, so one static file.
 * - Funnel Sans: body, nav and buttons. Variable, so one file covers the
 *   400–700 range in use instead of four.
 * - Instrument Serif italic: the accent word in headings and the quotes. The
 *   same face the app uses for quotes.
 */
const funnelDisplay = Funnel_Display({
  subsets: ["latin"],
  weight: ["800"],
  variable: "--font-funnel-display",
  display: "swap",
});

const funnelSans = Funnel_Sans({
  subsets: ["latin"],
  variable: "--font-funnel-sans",
  display: "swap",
});

const instrumentSerif = Instrument_Serif({
  subsets: ["latin"],
  weight: ["400"],
  style: ["italic"],
  variable: "--font-instrument-serif",
  display: "swap",
});

export const metadata: Metadata = {
  // metadataBase makes every relative URL below (canonicals, OG images)
  // resolve to an absolute one — required for valid og:image tags.
  metadataBase: new URL(site.url),

  title: {
    default: `${site.name} · ${site.tagline}`,
    template: `%s · ${site.shortTitle}`,
  },
  description: site.metaDescription,
  applicationName: site.name,
  authors: [{ name: site.publisher }],
  creator: site.publisher,
  publisher: site.publisher,

  keywords: [
    "Pearmo",
    "anonymous dating app",
    "dating app Sri Lanka",
    "Colombo dating",
    "personality matching",
    "Big Five dating app",
    "no swiping dating app",
    "safe dating app Sri Lanka",
    "psychology matched dating",
    "private dating app",
  ],

  category: "Dating",
  classification: "Dating and social networking",

  alternates: {
    canonical: "/",
    languages: {
      "en-LK": "/",
      // x-default is the fallback served to users whose language matches no
      // other hreflang entry. Present from day one so adding /si later only
      // means adding a key.
      "x-default": "/",
    },
  },

  openGraph: {
    type: "website",
    siteName: site.name,
    locale: site.locale,
    url: "/",
    title: `${site.name} · ${site.tagline}`,
    description: site.metaDescription,
    // The image itself is generated by app/opengraph-image.tsx.
  },

  twitter: {
    card: "summary_large_image",
    title: `${site.name} · ${site.tagline}`,
    description: site.metaDescription,
  },

  // Pre-launch site: index it, but keep AI/search snippet limits generous so
  // the value proposition can actually be quoted in results and AI answers.
  robots: isProductionSite
    ? {
        index: true,
        follow: true,
        googleBot: {
          index: true,
          follow: true,
          "max-image-preview": "large",
          "max-snippet": -1,
          "max-video-preview": -1,
        },
      }
    : // Preview deployments must never be indexed — duplicate content that
      // competes with the real domain.
      { index: false, follow: false },

  verification: {
    ...(verification.google ? { google: verification.google } : {}),
    ...(verification.bing ? { other: { "msvalidate.01": verification.bing } } : {}),
  },

  formatDetection: { telephone: false, address: false, email: false },

  // `capable: false`, explicitly: Next defaults it to true whenever an
  // appleWebApp object exists, which emits mobile-web-app-capable and makes
  // Share → Add to Home Screen open this marketing site full-screen like the
  // app. The installable app is app.pearmo.com.
  appleWebApp: {
    capable: false,
    title: site.name,
  },

  other: {
    // Dating service — an explicit adult-content rating, not a family site.
    rating: "adult",
    "apple-mobile-web-app-title": site.name,
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: site.themeColor },
    { media: "(prefers-color-scheme: dark)", color: site.themeColor },
  ],
  colorScheme: "light",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang={site.lang}
      className={`${funnelDisplay.variable} ${funnelSans.variable} ${instrumentSerif.variable}`}
    >
      <body className="bg-paper text-ink font-sans antialiased">
        {/* Keyboard and screen-reader users get past the fixed nav in one tab. */}
        <a
          href="#main"
          className="sr-only focus:not-sr-only focus:fixed focus:top-4 focus:left-4 focus:z-100 focus:rounded-full focus:bg-ink focus:px-5 focus:py-3 focus:text-sm focus:font-semibold focus:text-lime"
        >
          Skip to content
        </a>

        {/* The QR code's shape, defined once for every QR on the page. */}
        {site.webAppUrl && <QrDefs />}

        {children}

        {/* Smooth scrolling and scroll animations, loaded once the page is
            idle. Renders nothing; the page is complete without it. */}
        <Motion />

        {/* Site-wide entity graph. Page-specific schema lives on each page. */}
        <OrganizationSchema />
        <WebSiteSchema />

        {/* Cookieless — no consent banner required, and Speed Insights reports
            real-user Core Web Vitals, which is a ranking signal. */}
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  );
}
