import type { Metadata, Viewport } from "next";
import { Archivo, Azeret_Mono, Fraunces } from "next/font/google";
import { Analytics } from "@vercel/analytics/next";
import { SpeedInsights } from "@vercel/speed-insights/next";

import { OrganizationSchema, WebSiteSchema } from "@/components/seo/JsonLd";
import { isProductionSite, site, verification } from "@/lib/site";
import "./globals.css";

/**
 * Fonts are self-hosted by next/font at build time. This replaces the two
 * preconnects plus a render-blocking stylesheet the original page used, and
 * `display: swap` with automatic fallback metrics removes the layout shift
 * that came with them.
 */
const archivo = Archivo({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  style: ["normal", "italic"],
  variable: "--font-archivo",
  display: "swap",
});

const fraunces = Fraunces({
  subsets: ["latin"],
  weight: ["400", "500"],
  style: ["italic"],
  variable: "--font-fraunces",
  display: "swap",
});

const azeret = Azeret_Mono({
  subsets: ["latin"],
  weight: ["400", "500"],
  variable: "--font-azeret",
  display: "swap",
});

export const metadata: Metadata = {
  // metadataBase makes every relative URL below (canonicals, OG images)
  // resolve to an absolute one — required for valid og:image tags.
  metadataBase: new URL(site.url),

  title: {
    default: `${site.name} — ${site.tagline}`,
    template: `%s · ${site.shortTitle}`,
  },
  description: site.metaDescription,
  applicationName: site.name,
  authors: [{ name: site.publisher }],
  creator: site.publisher,
  publisher: site.publisher,

  keywords: [
    "Pearmo",
    "anonymous dating app",
    "dating app Sri Lanka",
    "Colombo dating",
    "personality matching",
    "Big Five dating app",
    "no swiping dating app",
    "verified dating app",
    "psychology matched dating",
    "private dating app",
  ],

  category: "Dating",
  classification: "Dating and social networking",

  alternates: {
    canonical: "/",
    languages: {
      "en-LK": "/",
      // x-default is the fallback served to users whose language matches no
      // other hreflang entry. Present from day one so adding /si later only
      // means adding a key.
      "x-default": "/",
    },
  },

  openGraph: {
    type: "website",
    siteName: site.name,
    locale: site.locale,
    url: "/",
    title: `${site.name} — ${site.tagline}`,
    description: site.metaDescription,
    // The image itself is generated by app/opengraph-image.tsx.
  },

  twitter: {
    card: "summary_large_image",
    title: `${site.name} — ${site.tagline}`,
    description: site.metaDescription,
  },

  // Pre-launch site: index it, but keep AI/search snippet limits generous so
  // the value proposition can actually be quoted in results and AI answers.
  robots: isProductionSite
    ? {
        index: true,
        follow: true,
        googleBot: {
          index: true,
          follow: true,
          "max-image-preview": "large",
          "max-snippet": -1,
          "max-video-preview": -1,
        },
      }
    : // Preview deployments must never be indexed — duplicate content that
      // competes with the real domain.
      { index: false, follow: false },

  verification: {
    ...(verification.google ? { google: verification.google } : {}),
    ...(verification.bing ? { other: { "msvalidate.01": verification.bing } } : {}),
  },

  formatDetection: { telephone: false, address: false, email: false },

  appleWebApp: {
    capable: true,
    title: site.name,
    statusBarStyle: "default",
  },

  other: {
    // Dating service — an explicit adult-content rating, not a family site.
    rating: "adult",
    "apple-mobile-web-app-title": site.name,
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: site.themeColor },
    { media: "(prefers-color-scheme: dark)", color: site.themeColor },
  ],
  colorScheme: "light",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang={site.lang}
      className={`${archivo.variable} ${fraunces.variable} ${azeret.variable}`}
    >
      <body className="bg-bg text-ink font-sans antialiased">
        {/* Keyboard and screen-reader users get past the fixed nav in one tab. */}
        <a
          href="#main"
          className="sr-only focus:not-sr-only focus:fixed focus:top-4 focus:left-4 focus:z-[100] focus:rounded-full focus:bg-ink focus:px-5 focus:py-3 focus:text-sm focus:font-semibold focus:text-white"
        >
          Skip to content
        </a>

        {children}

        {/* Site-wide entity graph. Page-specific schema lives on each page. */}
        <OrganizationSchema />
        <WebSiteSchema />

        {/* Cookieless — no consent banner required, and Speed Insights reports
            real-user Core Web Vitals, which is a ranking signal. */}
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  );
}
